// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhiJJdPAat-Ej9OSDjiKq0NIljVMwCRuQ',
    appId: '1:1073681408732:web:dfb6faef7127220e368a19',
    messagingSenderId: '1073681408732',
    projectId: 'sound-match-app',
    authDomain: 'sound-match-app.firebaseapp.com',
    storageBucket: 'sound-match-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbnjjuwLCYouKIx-gHYpPnwIsNgQR3U0A',
    appId: '1:1073681408732:android:c025dd6d7ed66e0f368a19',
    messagingSenderId: '1073681408732',
    projectId: 'sound-match-app',
    storageBucket: 'sound-match-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbOhl9T5zHdIS38xr72u930V44E9JwF4U',
    appId: '1:1073681408732:ios:2eb38b5198742cf1368a19',
    messagingSenderId: '1073681408732',
    projectId: 'sound-match-app',
    storageBucket: 'sound-match-app.appspot.com',
    androidClientId: '1073681408732-ju7cjsvd3k46sghdo7jh9aeererrhggf.apps.googleusercontent.com',
    iosClientId: '1073681408732-sprmh5v4095hm2300bssevol6d7v69nq.apps.googleusercontent.com',
    iosBundleId: 'com.example.soundApp',
  );
}
